// -----------------------------------------------------------------------------
// Example: Validate Master Slides Have Layouts Before Saving PPTX
//
// Description:
// This console application loads a PowerPoint PPTX file using Aspose.Slides for .NET,
// verifies that each master slide contains at least one layout slide, adds a default
// title layout when missing, and saves the updated presentation. It ensures the PPTX
// structure is valid before further processing or distribution.
//
// Keywords:
// C#, PowerPoint, PPTX, Aspose.Slides for .NET, master slide validation, layout slide, add default layout
//
// Use Cases:
// - Pre‑processing presentations to guarantee required master‑layout structure.
// - Automated cleanup of PPTX files generated by third‑party tools.
// - Preparing presentations for publishing pipelines that require at least one layout per master.
// Tested and Verified with Aspose.Slides for .NET v26.9.0.
// -----------------------------------------------------------------------------
using System;
using System.IO;

namespace AsposeSlidesValidationExample
{
    class Program
    {
        static void Main(string[] args)
        {
            string inputPath = Path.Combine(Environment.CurrentDirectory, "input.pptx");
            string outputPath = Path.Combine(Environment.CurrentDirectory, "output.pptx");

            if (!File.Exists(inputPath))
            {
                Console.WriteLine("Input file not found: " + inputPath);
                return;
            }

            Aspose.Slides.Presentation presentation = null;
            try
            {
                presentation = new Aspose.Slides.Presentation(inputPath);
            }
            catch (Aspose.Slides.PptxUnsupportedFormatException)
            {
                Console.WriteLine("The file format is not supported or the file is corrupted.");
                return;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Failed to load presentation: " + ex.Message);
                return;
            }

            try
            {
                int masterCount = presentation.Masters.Count;
                for (int i = 0; i < masterCount; i++)
                {
                    Aspose.Slides.IMasterSlide master = presentation.Masters[i];
                    Aspose.Slides.IMasterLayoutSlideCollection layoutSlides = master.LayoutSlides;

                    if (layoutSlides.Count == 0)
                    {
                        // Add a default Title layout when the master has no layouts.
                        Aspose.Slides.ILayoutSlide newLayout = layoutSlides.Add(Aspose.Slides.SlideLayoutType.Title, "Default Title Layout");
                        Console.WriteLine($"Added default Title layout to master index {i}.");
                    }
                }

                presentation.Save(outputPath, Aspose.Slides.Export.SaveFormat.Pptx);
                Console.WriteLine("Presentation saved successfully to: " + outputPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred while processing the presentation: " + ex.Message);
            }
            finally
            {
                if (presentation != null)
                {
                    presentation.Dispose();
                }
            }
        }
    }
}
