using System;
using System.IO;
using Aspose.Slides;
using Aspose.Slides.Export;

namespace DocumentPropertiesDemo
{
    class Program
    {
        static void Main()
        {
            // Define input and output file paths
            var inputPath = "data/input.pptx";
            var outputPath = "data/output.pptx";

            // Verify that the input file exists
            var fileExists = File.Exists(inputPath);
            if (!fileExists)
            {
                Console.WriteLine("Input file does not exist: " + inputPath);
                return;
            }

            // Open the presentation
            var presentation = new Aspose.Slides.Presentation(inputPath);

            // Access built‑in document properties
            var documentProperties = presentation.DocumentProperties;

            // Modify string properties
            documentProperties.Title = "Updated Presentation Title";
            documentProperties.Author = "John Doe";
            documentProperties.Subject = "Demo of String Constants";
            documentProperties.Comments = "Generated by Aspose.Slides";

            // Add or update a custom string property
            documentProperties.SetCustomPropertyValue("CustomString", "CustomValue");

            // Save the modified presentation
            presentation.Save(outputPath, Aspose.Slides.Export.SaveFormat.Pptx);

            // Release resources
            presentation.Dispose();

            Console.WriteLine("Presentation saved to: " + outputPath);
        }
    }
}