using System;
using System.IO;
using Aspose.Slides;
using Aspose.Slides.Export;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "input.pptx";
        string outputPath = "output.pptx";

        // Load existing presentation if it exists, otherwise create a new one
        Aspose.Slides.Presentation presentation;
        if (File.Exists(inputPath))
        {
            presentation = new Aspose.Slides.Presentation(inputPath);
        }
        else
        {
            presentation = new Aspose.Slides.Presentation();
        }

        // Ensure there are at least three slides for applying transitions
        while (presentation.Slides.Count < 3)
        {
            presentation.Slides.AddEmptySlide(presentation.Slides[0].LayoutSlide);
        }

        // Apply better slide transitions
        presentation.Slides[0].SlideShowTransition.Type = Aspose.Slides.SlideShow.TransitionType.Fade;
        presentation.Slides[0].SlideShowTransition.AdvanceOnClick = true;
        presentation.Slides[0].SlideShowTransition.AdvanceAfterTime = 3000u;

        presentation.Slides[1].SlideShowTransition.Type = Aspose.Slides.SlideShow.TransitionType.Cut;
        presentation.Slides[1].SlideShowTransition.AdvanceOnClick = true;
        presentation.Slides[1].SlideShowTransition.AdvanceAfterTime = 5000u;

        presentation.Slides[2].SlideShowTransition.Type = Aspose.Slides.SlideShow.TransitionType.Zoom;
        presentation.Slides[2].SlideShowTransition.AdvanceOnClick = true;
        presentation.Slides[2].SlideShowTransition.AdvanceAfterTime = 7000u;

        // Manage header/footer on the first slide
        Aspose.Slides.IBaseSlideHeaderFooterManager headerFooterManager = presentation.Slides[0].HeaderFooterManager;
        if (!headerFooterManager.IsFooterVisible)
        {
            headerFooterManager.SetFooterVisibility(true);
        }
        if (!headerFooterManager.IsSlideNumberVisible)
        {
            headerFooterManager.SetSlideNumberVisibility(true);
        }
        if (!headerFooterManager.IsDateTimeVisible)
        {
            headerFooterManager.SetDateTimeVisibility(true);
        }
        headerFooterManager.SetFooterText("Confidential");
        headerFooterManager.SetDateTimeText(DateTime.Now.ToString("yyyy-MM-dd"));

        // Modify built-in document properties
        Aspose.Slides.IDocumentProperties docProps = presentation.DocumentProperties;
        docProps.Author = "Aspose.Slides Demo";
        docProps.Title = "Real-time Editing Example";
        docProps.Subject = "Demo of slide transitions and header/footer";
        docProps.Comments = "Generated by Aspose.Slides";

        // Save the presentation
        presentation.Save(outputPath, Aspose.Slides.Export.SaveFormat.Pptx);
        presentation.Dispose();
    }
}