// -----------------------------------------------------------------------------
// Example: Save MathML Byte Array to XML File Using FileStream
//
// Description:
// This console application demonstrates how to write a captured MathML byte
// array to an XML file using a System.IO.FileStream. It ensures the output
// directory exists, handles potential I/O exceptions, and closes the stream
// properly. The code is useful for developers working with MathML data
// extraction or conversion in .NET environments.
//
// Keywords:
// C#, PowerPoint, PPTX, Aspose.Slides for .NET, MathML, FileStream, XML, byte array
//
// Use Cases:
// - Exporting MathML content generated by a presentation to a standalone XML file.
// - Persisting MathML data retrieved from a web service for later processing.
// - Saving MathML snippets extracted from slides for documentation purposes.
// Tested and Verified with Aspose.Slides for .NET v26.9.0.
// -----------------------------------------------------------------------------
using System;
using System.IO;

namespace MathMLFileSaver
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // Sample MathML byte array (replace with actual captured data)
            byte[] mathMlBytes = System.Text.Encoding.UTF8.GetBytes("<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mi>x</mi><mo>=</mo><mn>5</mn></math>");

            // Define output directory and file name
            string outputDirectory = Path.Combine(Directory.GetCurrentDirectory(), "Output");
            string outputFileName = "captured_mathml.xml";
            string outputPath = Path.Combine(outputDirectory, outputFileName);

            try
            {
                // Ensure the output directory exists
                if (!Directory.Exists(outputDirectory))
                {
                    Directory.CreateDirectory(outputDirectory);
                }

                // Write the byte array to the XML file using FileStream
                using (FileStream fileStream = new FileStream(outputPath, FileMode.Create, FileAccess.Write))
                {
                    fileStream.Write(mathMlBytes, 0, mathMlBytes.Length);
                }

                Console.WriteLine("MathML has been successfully saved to: " + outputPath);
            }
            catch (IOException ioEx)
            {
                Console.Error.WriteLine("I/O error while saving MathML: " + ioEx.Message);
            }
            catch (UnauthorizedAccessException uaEx)
            {
                Console.Error.WriteLine("Access denied while saving MathML: " + uaEx.Message);
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("Unexpected error: " + ex.Message);
            }
        }
    }
}
