// -----------------------------------------------------------------------------

// Tested and verified with Aspose.Slides for .NET 26.8.0.
// Example: Convert PPTX to animated GIF loop using C#

//

// Description:

// Demonstrates how to convert a PPTX presentation to an animated GIF loop using

// C# and Aspose.Slides for .NET. The example loads a PowerPoint file, configures

// GIF export options such as frame size, delay, and transition frame rate, and

// saves the result as a looping animated GIF. This pattern can be used to

// automate PPTX-to-GIF conversions, integrate presentation processing into

// .NET applications, or generate GIF previews of slides.

//

// Keywords:

// C#, PowerPoint, PPTX, GIF, Animated, Loop, Aspose.Slides for .NET, Convert,

// Presentation Processing, Office Automation

//

// Use Cases:

// - Automate conversion of PPTX files to looping animated GIFs.

// - Build C# utilities for creating GIF previews of presentations.

// - Integrate slide-to-GIF functionality into .NET applications.

// - Validate and test PowerPoint content by generating visual GIF outputs.

// -----------------------------------------------------------------------------

using System;

using System.IO;

using Aspose.Slides;

using Aspose.Slides.Export;



namespace ConvertPptxToGif

{

    class Program

    {

        static void Main(string[] args)

        {

            // Input and output file paths

            string inputPath = "input.pptx";

            string outputPath = "output.gif";



            // Verify that the input file exists

            if (!File.Exists(inputPath))

            {

                Console.WriteLine("Input file does not exist: " + inputPath);

                return;

            }



            try

            {

                // Load the presentation

                Aspose.Slides.Presentation presentation = new Aspose.Slides.Presentation(inputPath);



                // Configure GIF export options

                Aspose.Slides.Export.GifOptions gifOptions = new Aspose.Slides.Export.GifOptions();

                gifOptions.FrameSize = new System.Drawing.Size(960, 720); // Desired GIF size

                gifOptions.DefaultDelay = 1000; // Delay per frame in milliseconds

                gifOptions.TransitionFps = 25; // Frames per second for transitions

                // Looping indefinitely is the default behavior for GIFs generated by Aspose.Slides



                // Save the presentation as an animated GIF

                presentation.Save(outputPath, Aspose.Slides.Export.SaveFormat.Gif, gifOptions);



                // Dispose the presentation

                presentation.Dispose();



                Console.WriteLine("Conversion completed successfully.");

            }

            catch (NotSupportedException)

            {

                // Format not supported

                Console.WriteLine("The provided file format is not supported for conversion.");

            }

            catch (Exception ex)

            {

                // Handle other exceptions (e.g., file access issues, Aspose.Slides errors)

                Console.WriteLine("An error occurred: " + ex.Message);

            }

        }

    }

}

