using System;
using System.IO;
using Aspose.Slides;
using Aspose.Slides.Export;

namespace ConvertPptxToGif
{
    class Program
    {
        static void Main(string[] args)
        {
            // Input and output file paths
            string inputPath = "input.pptx";
            string outputPath = "output.gif";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine("Input file does not exist: " + inputPath);
                return;
            }

            try
            {
                // Load the presentation
                Aspose.Slides.Presentation presentation = new Aspose.Slides.Presentation(inputPath);

                // Configure GIF export options
                Aspose.Slides.Export.GifOptions gifOptions = new Aspose.Slides.Export.GifOptions();
                gifOptions.FrameSize = new System.Drawing.Size(960, 720); // Desired GIF size
                gifOptions.DefaultDelay = 1000; // Delay per frame in milliseconds
                gifOptions.TransitionFps = 25; // Frames per second for transitions
                // Looping indefinitely is the default behavior for GIFs generated by Aspose.Slides

                // Save the presentation as an animated GIF
                presentation.Save(outputPath, Aspose.Slides.Export.SaveFormat.Gif, gifOptions);

                // Dispose the presentation
                presentation.Dispose();

                Console.WriteLine("Conversion completed successfully.");
            }
            catch (NotSupportedException)
            {
                // Format not supported
                Console.WriteLine("The provided file format is not supported for conversion.");
            }
            catch (Exception ex)
            {
                // Handle other exceptions (e.g., file access issues, Aspose.Slides errors)
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }
    }
}