using System;
using System.IO;
using Aspose.Slides;
using Aspose.Slides.Export;

namespace AsposeSlidesGifLoopExample
{
    class Program
    {
        static void Main(string[] args)
        {
            // Input and output file paths
            string inputPath = "input.pptx";
            string outputPath = "output.gif";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.WriteLine("Input file does not exist: " + inputPath);
                return;
            }

            try
            {
                // Load the presentation
                using (Presentation presentation = new Presentation(inputPath))
                {
                    // Create GIF export options
                    GifOptions gifOptions = new GifOptions();

                    // The GifOptions class does not expose a LoopCount property.
                    // LoopCount cannot be set directly; infinite looping is the default behavior
                    // for GIFs generated by Aspose.Slides. If required, this limitation should be noted.
                    // Comment: LoopCount property not available in Aspose.Slides.Export.GifOptions.

                    // Example of setting other GIF options (optional)
                    gifOptions.DefaultDelay = 1000; // 1 second per frame
                    gifOptions.ExportHiddenSlides = false;

                    // Save the presentation as an animated GIF
                    presentation.Save(outputPath, SaveFormat.Gif, gifOptions);
                }

                // Verify that the GIF file was created
                if (File.Exists(outputPath))
                {
                    Console.WriteLine("GIF file created successfully: " + outputPath);
                    // Placeholder: inspect GIF metadata here if needed.
                }
                else
                {
                    Console.WriteLine("Failed to create GIF file.");
                }
            }
            catch (NotSupportedException ex)
            {
                // Handle unsupported format exception
                Console.WriteLine("The requested format is not supported: " + ex.Message);
            }
            catch (Exception ex)
            {
                // General exception handling
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }
    }
}