using System;
using System.IO;
using Aspose.Slides;
using Aspose.Slides.Export;

class Program
{
    static void Main(string[] args)
    {
        // Determine input file path (default or from command line)
        string inputPath = "input.pptx";
        if (args.Length > 0)
        {
            inputPath = args[0];
        }

        // Verify that the input file exists
        if (!File.Exists(inputPath))
        {
            Console.WriteLine("Input file does not exist: " + inputPath);
            return;
        }

        try
        {
            // Load the presentation
            using (Presentation pres = new Presentation(inputPath))
            {
                // Create GIF export options
                GifOptions gifOptions = new GifOptions();

                // NOTE: The LoopCount property is not available in the current Aspose.Slides version.
                // Non‑looping GIFs are generated by default behavior; explicit LoopCount cannot be set.

                // Define output path with .gif extension
                string outputPath = Path.ChangeExtension(inputPath, ".gif");

                // Save the presentation as an animated GIF
                pres.Save(outputPath, Aspose.Slides.Export.SaveFormat.Gif, gifOptions);
                Console.WriteLine("GIF saved to: " + outputPath);
            }
        }
        catch (NotSupportedException)
        {
            // Handle case where GIF format is not supported
            Console.WriteLine("GIF format not supported.");
        }
        catch (Exception ex)
        {
            // General exception handling
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}